FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY worker_app.py .

CMD ["uvicorn", "worker_app:app", "--host", "0.0.0.0", "--port", "8001"]
