FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY scheduler_app.py .

CMD ["uvicorn", "scheduler_app:app", "--host", "0.0.0.0", "--port", "8000"]